[server]
maxUploadSize = 50
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[runner]
fastReruns = true

[client]
# Masquer la navigation automatique des pages Streamlit
showSidebarNavigation = false

[theme]
base = "dark"
